:doctype: book
:doctitle:
:docdate: January 25, 2018
:author: Jerod Gawne
:email: jerodgawne@gmail.com
:revnumber: 0.0.4
:revdate: May 08, 2018
:revremark: updated email, added source for optional, formatting
:description: code/information on setting up git
:keywords: linux, cookbook, snippets, git
:source-highlighter: highlight.js
:sectanchors:
:sectlinks:
:sectnums:
:toc:

= Git Cookbook

Code & Information on setting up git on a new computer.

== Windows
[source,bash,numbered]
git config --global user.name "<First Last>"
git config --global user.email "<user@domain.ext>"
git config --global core.autocrlf false
gpg --import "<gpg-location>"
git config --global user.signingkey <keyid>
git config --global commit.gpgsign true
git config --global gpg.program "C:\Program Files (x86)\GnuPG\bin\gpg.exe"
git config --global core.eol lf
git config --global core.compression 9
git config --global core.looseCompression 9
git config --global credential.helper 'cache --timeout=3600'

== Linux
[source,bash,numbered]
git config --global user.name "<First Last>"
git config --global user.email "<user@domain.ext>"
git config --global core.autocrlf false
gpg --import "<gpg-location>"
git config --global user.signingkey <keyid>
git config --global commit.gpgsign true
git config --global core.eol lf
git config --global core.compression 9
git config --global core.looseCompression 9
git config --global credential.helper 'cache --timeout=3600'

== Reset branch to remote
[source,bash,numbered]
git reset --hard HEAD

== Push Commits to Another Branch
[source,bash]
git push origin branch1:branch2

Or

[source,bash]
git push <remote> <branch with new changes>:<branch you are pushing to> 

== Undo/Redo a Commits
[source,bash]
git commit -m "Something terribly misguided"             
git reset HEAD~                                          
<< edit files as necessary >>                              
git add ...                                              
git commit -c ORIG_HEAD                                  

This is what you want to undo
This leaves your working tree (the state of your files on disk) unchanged but undoes the commit and leaves the changes you committed unstaged (so they'll appear as "Changes not staged for commit" in git status, and you'll need to add them again before committing). If you only want to add more changes to the previous commit, or change the commit message1, you could use git reset --soft HEAD~ instead, which is like git reset HEAD~ (where HEAD~ is the same as HEAD~1) but leaves your existing changes staged.
Make corrections to working tree files.
git add anything that you want to include in your new commit.
Commit the changes, reusing the old commit message. reset copied the old head to .git/ORIG_HEAD; commit with -c ORIG_HEAD will open an editor, which initially contains the log message from the old commit and allows you to edit it. If you do not need to edit the message, you could use the -C option.
Beware however that if you have added any new changes to the index, using commit --amend will add them to your previous commit.

If the code is already pushed to your server and you have permissions to overwrite history (rebase) then:

[source,bash]
git push origin master --force

.Reference
https://jamesmckay.net/2016/02/signing-git-commits-with-gpg-on-windows/[James McKay] +
https://git-scm.com/book/id/v2/Git-Tools-Signing-Your-Work[Git-Scm] +
https://stackoverflow.com/a/19213999/4434405[Stack Overflow] +
https://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server[Stack Overflow] +
https://stackoverflow.com/a/927386/4434405[Stack Overflow] +
